version = 0.1

[default.deploy.parameters]
stack_name = "tweeter-server"
s3_bucket = "amzn-s3-sam-tweeter-bucket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []